[aws]
aws_region_name = eu-central-1

[aliases]
ssh = ssh {CFN_USER}@{MASTER_IP} {ARGS}

[global]
cluster_template = default
update_check = true
sanity_check = true

[cluster default]
key_name = msalazar-frankfurt
scheduler = slurm
master_instance_type = c5n.large
base_os = alinux2
vpc_settings = default
queue_settings = compute

[vpc default]
vpc_id = vpc-0ccebb0c2e8111973
master_subnet_id = subnet-0dcf4eb823a056a3b
compute_subnet_id = subnet-0fb0ea91b59fb1ed4
use_public_ips = false

[queue compute]
enable_efa = false
compute_resource_settings = default

[compute_resource default]
instance_type = c5n.18xlarge

